repos:
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.2.1
    hooks:
      - id: fmt
      - id: test
      - id: build
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: forbid-submodules
  - repo: local
    hooks:
      - id: cargo-check
        name: Cargo check
        entry: cargo +nightly check
        language: system
        args: ["--target", "riscv64gc-unknown-linux-musl"]
        files: ^src/
        pass_filenames: false
      - id: cargo-clippy
        name: Cargo clippy
        entry: cargo +nightly clippy
        language: system
        args: ["--target", "riscv64gc-unknown-linux-musl"]
        files: ^src/
        pass_filenames: false
