[package]
name = "nanokvm-control-api"
version = "0.1.0"
edition = "2024"

[dependencies]
pcf857x = "0.5.0"
linux-embedded-hal = "0.4"
tiny_http = "0.12.0"
log = "0.4"
flexi_logger = "0.31.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
